name: Deploy app to Amazon EKS

on:
  workflow_dispatch:
    inputs:
      appName:
        description: ' The name of application'
        required: true
      clusterName:
        description: ' The name of your EKS cluster'
        required: true
      region:
        description: 'The AWS region where the cluster will be deployed'
        required: true
      image:
        description: 'Image for deployment'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-region: us-east-1
          
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

     # update the context to the EKS cluster of app
      - name: Update kubeconfig
        run: |
          role=$(aws sts assume-role --role-arn arn:aws:iam::625011733915:role/idp-demo --role-session-name my-seesion-test1)
          export AWS_ACCESS_KEY_ID=$(echo $role | jq -r .Credentials.AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $role | jq -r .Credentials.SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $role | jq -r .Credentials.SessionToken)
          aws eks update-kubeconfig --name ${{ github.event.inputs.clusterName }} --region ${{ github.event.inputs.region }}
          # roleinfo=$(aws sts get-caller-identity)
          # arn=$(echo $roleinfo | jq -r '.Arn')
          aws eks create-access-entry --cluster-name ${{ github.event.inputs.clusterName }}  --principal-arn arn:aws:iam::899578970796:user/backstage-workshop --region ${{ github.event.inputs.region }}  --type STANDARD --username arn:aws:iam::899578970796:user/backstage-workshop
          aws eks associate-access-policy --cluster-name ${{ github.event.inputs.clusterName }}  --region ${{ github.event.inputs.region }}   --principal-arn arn:aws:iam::899578970796:user/backstage-workshop --access-scope type=cluster --policy-arn arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
        continue-on-error: true
      - name: Deployment app
        run: |
          export IMAGE=${{ github.event.inputs.image }}
          export APP_NAME=${{ github.event.inputs.appName }}
          envsubst < app/deployment.yaml | kubectl apply -f - 
